#! /bin/bash

filename="$1"
q="$2"
N="$3"
M="$4"

if [ -z "$filename" ] || [ -z "$q" ] || [ -z "$N" ] || [ -z "$M" ]; then
	echo "Usage: ./runpar <filename> <q> <N> <M>"
	exit 1
fi

numprocs=`expr $N \* $M`
#echo "numprocs=$numprocs"

mpirun --hostfile hostfile.txt \
	-np ${numprocs} -mca btl '^openib' ./countblocks \
	$filename $q $N $M
